source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'BusinessAbSoft' do
    pod 'NVActivityIndicatorView'
    pod 'ExpandingMenu', '~> 0.4'
    pod 'XLPagerTabStrip', '~> 8.0'
    pod 'Charts'
    pod 'SwiftCop'
    
    pod 'PasswordTextField'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'PullToRefreshKit'
    pod 'CRNetworkButton'
    
    pod 'ActionSheetPicker-3.0'
    pod 'DKImagePickerController'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'TPKeyboardAvoiding'
    pod 'WYPopoverController'
    
    #    pod 'KUIPopOver'
    #    pod 'SwiftyPickerPopover'
    #    pod 'SDWebImage', '~> 4.0'
    #    pod 'SCLAlertView'
    #    pod 'SwiftMessages'
end

